name: Deploy to GitHub Pages on merge
'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: npm install && node ci/geojson.js && npm run generate
        env:
          NUXT_PUBLIC_MAPBOX_STYLE_URL_LIGHT: ${{ vars.NUXT_PUBLIC_MAPBOX_STYLE_URL_LIGHT }}
          NUXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ vars.NUXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}
          SUPABASE_ANON_KEY: ${{ vars.SUPABASE_ANON_KEY }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          # cname: maps.tenantresourcecenter.org