name: Deploy to GitHub Pages on merge
'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "NUXT_PUBLIC_MAPBOX_STYLE_URL : $NUXT_PUBLIC_MAPBOX_STYLE_URL"
          npm install && npm run generate
        env:
          NUXT_PUBLIC_MAPBOX_STYLE_URL: ${{ secrets.NUXT_PUBLIC_MAPBOX_STYLE_URL }}
          NUXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.NUXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public