name: Deploy to GitHub Pages on merge
'on':
  push:
    branches:
      - main
env:
  NUXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ vars.NUXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}
  NUXT_PUBLIC_MAPBOX_STYLE_URL: ${{ vars.NUXT_PUBLIC_MAPBOX_STYLE_URL }}
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run generate
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public